version: "3"

services:
    backend:
        container_name: task-backend
        build:
            target: watcher
            args:
                - WEATHER_KEY=${WEATHER_KEY}
                - SECRET_KEY=${SECRET_KEY}
        ports:
            - 5000:5000
        volumes:
            - .:/app
        networks:
            - task
networks:
    task:
